spring.application.name=Lab6
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Lab6;encrypt=false
spring.datasource.username=sa
spring.datasource.password=Sql@123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

app.jwt.secret=4c1e5e0a13083773fea8815a182c21f01178bd08d99b6ca799eb93bddb457d56779987671186688cd7e60e8e92d6d2975a9889a75a524ea162f643be11129ad7==
app.jwt.expiration-ms=3600000

# Swagger UI customization
springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.custom-css=/swagger-ui-custom.css
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
