spring.application.name=demo

# SQL Server configuration (update with your actual values)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=FuMiniHotelSystem;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Sql@123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

# Staff account (update with real credentials)
app.staff.email=staff@gmail.com
app.staff.password=$2a$10$EH/g3DcPBry0ngdCxlZF3eirvzcuM6vxuCAwAbWSlCYirNMJxO7Si
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# JWT
# Generate a base64 secret (minimum 256-bit). Example: openssl rand -base64 32
app.jwt.secret=3035df23d52d903b19104338fb299e7794b4a22d97ba0138ccb9b783966cd27094ae026c1fc4ef97bc93333d5f2935038f92734a9c0c3cd59052c5d8cc736745
app.jwt.expiration-minutes=60
